version: 0.2

batch:
  build-list:
    - identifier: build1
      env:
        variables:
          GOOS: darwint
          GOARCH: amd64
    - identifier: build2
      env:
        variables:
          GOOS: darwint
          GOARCH: arm64

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - mvn install
artifacts:
  files:
    - target/javawebdemo.war
    - appspec.yml
    - scripts/**/*
  discard-paths: no
